db = db.getSiblingDB('swallowweb');
load("mongo-tb-alarmmeta.js");
load("mongo-tb-consumeridresource.js");
load("mongo-tb-consumerserverresource.js");
load("mongo-tb-producerserverresource.js");
load("mongo-tb-topicresource.js");
load("mongo-tb-ipresource.js");
load("mongo-tb-applicationresource.js");
load("mongo-tb-user.js");
load("mongo-tb-groupresource.js");
load("mongo-tb-messagedump.js");
load("mongo-tb-mongoresource.js");
